### ISSUE TITLE
Flaky breathe warning

### ISSUE THREAD

**Issue by arwedus** [michaeljones/breathe#783]
I get the following warning, which only appears in a certain project, but does not appear with the same code extracted to a sample project (which is why I can't provide the example project here):

```
/doc-root/common/interfaces/aracom_interfaces/doc/a_interface.rst: WARNING: Internal C++ domain error during symbol merging.
ourChild:
  MAX_NUM_CONTOUR_POINTS: std::size_t MAX_NUM_CONTOUR_POINTS	(common/interfaces/aracom_interfaces/doc/a_interface)

otherChild:
  MAX_NUM_CONTOUR_POINTS: std::size_t MAX_NUM_CONTOUR_POINTS	(common/interfaces/aracom_interfaces/doc/a_interface)
```

The C++ header looks like this (I had to mangle names):

```cpp
namespace aracom_interfaces {

template <std::size_t MAX_NUM_CONTOUR_POINTS>
struct ObjectContourData {
  using Contour = Constrained<
      math::ts_fixed_polygon::TsFixedPolygon<float, type_safe_matrix::VehicleCoords, MAX_NUM_CONTOUR_POINTS>,
      ValidTsFixedPolygon>;

  Contour contour;
};

}
```

so, lots of templates but that's it. The above struct is included once in the mentioned document (a_interface):

```
.. doxygenstruct:: aracom_interfaces::ObjectContourData
   :members:
```

Again, I wish I could build you an example project but I can't. The "internal C++ domain error" seems like an undescriptive error message, at least. It may be a bug because doxygen runs over this file without warnings.
