### ISSUE TITLE
Code highlighting similar to breathe

### ISSUE THREAD

**Issue by LecrisUT** [michaeljones/breathe#909]
Just want to point out that the default code highlighting is rather bland without `breathe.css`. What I want to point out is that this css file has some specific customizations that should be included by default:
```css
.highlight {
    /* desaturate that ugly yellow color used by most other theme's code snippets */
    background-color: var(--color-api-background); /* for light theme only */
}

.sig.c   .k, .sig.c   .kt,
.sig.cpp .k, .sig.cpp .kt {
    color: var(--breathe-keyword-type-color);
}

.sig.c   .m,
.sig.cpp .m {
    color: var(--breathe-number-color);
}

.sig.c   .s, .sig.c   .sc,
.sig.cpp .s, .sig.cpp .sc {
    color: var(--breathe-str-char-color);
}

.sig > .n {
    color: var(--breathe-name-color);
}

/*
bugfix for multi-lined signatures
(see https://github.com/pradyunsg/furo/discussions/427 )
*/
.sig {
    padding-left: 0.5em;
    text-indent: revert;
}
```

I am not familiar enough with `css` to quite understand that is done over there, but it would be great to expose these, so that the only change needed is like:
```css
:root {
    --color-brand-primary-light: hsl(205deg, 52%, 39%);
    --color-brand-primary-dark: hsl(205deg, 65%, 65%);
    --breathe-str-char-color-dark: hsl(41, 85%, 46%);
    --breathe-str-char-color-light: hsl(41, 89%, 37%);
    --breathe-keyword-type-color-dark: hsl(256, 100%, 65%);
    --breathe-keyword-type-color-light: hsl(276, 85%, 29%);
    --breathe-number-color-dark: hsl(157, 81%, 50%);
    --breathe-number-color-light: hsl(157, 93%, 32%);
    --breathe-name-color-dark: hsl(88, 72%, 56%);
    --breathe-name-color-light: hsl(88, 100%, 28%);
}
```
